### ISSUE TITLE
Qs about self make textures

### ISSUE THREAD

**Issue by shenkongsk** [roracle/SF-resources#2]
I didn‘t find the place which can chat with you, so I came here.
I’m not an english speaker, so my english would probably be VERY bad.
And I know nothing about programming.
If I want to make some self-made item textures, the steps below are right?
1.make PNGs and JSONs and put it in
2.pair the numbers in models/item ‘s xxx.json and item-models.yml
(Q:Must I make sure all the texts in models/item’s xxx
.json ALL THE SAME?)
3.The server’s owner’s job
I still have a few questions.
1.Why does the JSON in models of Android is not the same as the one with weapons and other things?
2.If I just write fewest text like JSON of weapons ,would it be effective?
Hope you see this.( ･᷄ὢ･᷅ )

**Comment by shenkongsk** [comment]
PS：Just want to find the way to make self-made textrues
And do you know about the resourcepack of other sf addons? Such as infinitely-expansion’s and other addons resourcespack?

**Comment by roracle** [comment]
This pack was copied from another. I'm learning as I go, and I barely work on this pack to begin with.
